# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destructible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='expire',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(70, 'The value should be less than %(limit_value)s.')]),
        ),
    ]
