# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:28
from __future__ import unicode_literals

import destructible.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destructible', '0002_auto_20160421_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='docfile',
            field=models.FileField(upload_to='uploads', validators=[destructible.models.Attachment.validate_file_extension]),
        ),
    ]
