# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destructible', '0003_auto_20160421_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='docfile',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
